# Generated by Django 4.2.13 on 2024-07-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0004_remove_barber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='description',
            field=models.TextField(default='Please add description'),
        ),
    ]
