# Generated by Django 4.2.13 on 2024-07-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='contact',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
