# Generated by Django 4.2.13 on 2024-07-08 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_alter_barber_user'),
        ('appointments', '0002_appointment_contact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 8, 19, 46, 28, 847303, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.time(8, 0)),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time', 'barber')},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='datetime',
        ),
    ]
